/*
 * Decompiled with CFR 0.152.
 */
public final class MenuChinhAvatar {
    public static String chuoiGiaTri;
    public static String tenNhanVat;
    public static String chuoiPhu;
    public static String var_java_lang_String_int;
    public static String var_java_lang_String_new;
    public static String var_java_lang_String_try;
    public static String var_java_lang_String_byte;
    public static String var_java_lang_String_case;
    public static String var_java_lang_String_char;
    public static String[] var_java_lang_String_arr_do;
    public static String var_java_lang_String_else;
    public static String var_java_lang_String_goto;
    public static String var_java_lang_String_long;
    public static String var_java_lang_String_this;
    public static String var_java_lang_String_void;
    public static String var_java_lang_String_break;
    public static String var_java_lang_String_catch;
    public static String var_java_lang_String_class;
    public static String var_java_lang_String_const;
    public static String var_java_lang_String_final;
    public static String var_java_lang_String_float;
    public static String var_java_lang_String_short;
    public static String var_java_lang_String_super;
    public static String[] var_java_lang_String_arr_if;
    public static String cfr_renamed_24;
    public static String cfr_renamed_22;
    public static String cfr_renamed_17;
    public static String cfr_renamed_29;
    public static String cfr_renamed_26;
    public static String cfr_renamed_27;
    public static String[] var_java_lang_String_arr_for;
    public static String cfr_renamed_25;
    public static String cfr_renamed_28;
    public static String cfr_renamed_31;
    public static String cfr_renamed_11;
    public static String cfr_renamed_32;
    public static String cfr_renamed_33;
    public static String cfr_renamed_39;
    public static String cfr_renamed_38;
    public static String cfr_renamed_34;
    public static String cfr_renamed_36;
    public static String cfr_renamed_40;
    public static String cfr_renamed_35;
    public static String cfr_renamed_41;
    public static String cfr_renamed_37;
    public static String cfr_renamed_19;
    public static String cfr_renamed_42;
    public static String cfr_renamed_43;
    public static String cfr_renamed_44;
    public static String cfr_renamed_45;
    public static String cfr_renamed_46;
    public static String a;
    public static String b;
    public static String c;
    public static String d;
    public static String e;
    public static String f;
    public static String g;
    public static String h;
    public static String i;
    public static String j;
    public static String k;
    public static String l;
    public static String[] var_java_lang_String_arr_int;
    public static String m;
    public static String n;
    public static String o;
    public static String p;
    public static String q;
    public static String r;
    public static String s;
    public static String t;
    public static String u;
    public static String v;
    public static String w;
    public static String x;
    public static String[] var_java_lang_String_arr_new;
    public static String[] var_java_lang_String_arr_try;
    public static String y;
    public static String z;
    public static String A;
    public static String B;
    public static String C;
    public static String D;
    public static String E;
    public static String F;
    public static String G;
    public static String H;
    public static String I;
    public static String J;
    public static String[] var_java_lang_String_arr_byte;
    public static String[] var_java_lang_String_arr_case;
    public static String K;
    public static String L;
    public static String[] var_java_lang_String_arr_char;
    public static String M;
    public static String N;
    public static String O;
    public static String P;
    public static String Q;
    public static String R;
    public static String S;
    public static String T;
    public static String U;
    public static String V;
    public static String W;
    public static String[][] var_java_lang_String_arr_arr_do;
    public static String X;
    public static String Y;
    public static String Z;
    public static String aa;
    public static String ab;
    public static String ac;
    public static String ad;
    public static String ae;
    public static String af;
    public static String ag;
    public static String ah;
    public static String ai;
    public static String aj;
    public static String ak;
    public static String al;
    public static String am;
    public static String an;
    public static String ao;
    public static String ap;
    public static String aq;
    public static String ar;
    public static String as;
    public static String at;
    public static String au;
    public static String av;
    public static String aw;
    public static String ax;
    public static String FormCaiDatCauCa;
    public static String az;
    public static String aA;
    public static String aB;
    public static String aC;
    public static String aD;
    public static String aE;
    public static String aF;
    public static String aG;
    public static String[] var_java_lang_String_arr_else;
    public static String aH;
    public static String aI;
    public static String aJ;
    public static String aK;
    public static String aL;
    public static String aM;
    public static String aN;
    public static String aO;
    public static String aP;
    public static String aQ;
    public static String[] var_java_lang_String_arr_goto;
    public static String aR;
    public static String aS;
    public static String aT;
    public static String aU;
    public static String aV;
    public static String aW;
    public static String[] var_java_lang_String_arr_long;
    public static String aX;
    public static String aY;
    public static String aZ;
    public static String ba;
    public static String bb;
    public static String bc;
    public static String bd;
    public static String be;
    public static String bf;
    public static String bg;
    public static String bh;
    public static String bi;
    public static String bj;
    public static String bk;
    public static String bl;
    public static String bm;
    public static String bn;
    public static String bo;
    public static String[] var_java_lang_String_arr_this;
    public static String bp;
    public static String bq;
    public static String br;
    public static String bs;
    public static String[] var_java_lang_String_arr_void;
    public static String bt;
    public static String bu;
    public static String bv;
    public static String bw;
    public static String GameCanvas;
    public static String[][] var_java_lang_String_arr_arr_if;
    private static int[] mangSoNguyen;
    public static String by;
    public static String[] var_java_lang_String_arr_break;
    public static String bz;
    public static String[] var_java_lang_String_arr_catch;
    public static String[] var_java_lang_String_arr_class;
    public static String bA;
    public static String bB;
    public static String bC;
    public static String bD;
    public static String bE;
    public static String bF;
    public static String bG;
    public static String bH;
    public static String bI;
    public static String bJ;
    public static String bK;
    public static String bL;
    public static String bM;
    public static String bN;
    public static String bO;
    public static String bP;
    public static String MenuChinhAvatar;
    public static String bR;
    public static String bS;
    public static String bT;
    public static String bU;
    public static String bV;
    public static String bW;
    public static String bX;
    public static String bY;
    public static String bZ;
    public static String ca;
    public static String cb;
    public static String cc;
    public static String cd;
    public static String ce;
    public static String cf;
    public static String cg;
    public static String ch;
    public static String ci;
    public static String cj;
    public static String ck;
    public static String cl;
    public static String cm;
    public static String FormCaiDatFarm;
    public static String co;
    public static String QuanLyRMS;
    public static String[] var_java_lang_String_arr_const;
    public static String cq;
    public static String cr;
    public static String cs;
    public static String ct;
    public static String cu;
    public static String cv;
    public static String cw;
    public static String cx;
    public static String cy;
    public static String cz;
    public static String cA;
    private static String[] var_java_lang_String_arr_super;
    public static String cB;
    public static String cC;
    public static String[] var_java_lang_String_arr_final;
    public static String cD;
    public static String cE;
    public static String cF;
    public static String cG;
    public static String cH;
    public static String cI;
    public static String cJ;
    public static String cK;
    public static String cL;
    public static String cM;
    public static String cN;
    public static String[][] var_java_lang_String_arr_arr_for;
    public static String cO;
    public static String cP;
    public static String cQ;
    public static String cR;
    public static String[] var_java_lang_String_arr_float;
    public static String cS;
    public static String cT;
    public static String cU;
    public static String cV;
    public static String cW;
    public static String cX;
    public static String cY;
    public static String cZ;
    public static String da;
    public static String db;
    public static String dc;
    public static String dd;
    public static String de;
    public static String df;
    public static String dg;
    public static String dh;
    public static String di;
    public static String dj;
    public static String dk;
    public static String dl;
    public static String dm;
    public static String[] var_java_lang_String_arr_short;
    public static String dn;
    public static String dp;

    public static String[] java_lang_String_arr_do() {
        String[] stringArray = new String[1];
        stringArray[0] = "Bạn có thể ra khỏi nơi này bằng cách đi đến nơi mũi tên chỉ";
        return stringArray;
    }

        public static String[][] java_lang_String_arr_arr_do() {
        String[][] stringArray = new String[3][];
        String[] stringArray2 = new String[2];
        stringArray2[0] = "Chào mừng bạn đến khu mua sắm, tại đây bạn có thể thỏa thích lựa chọn cho mình những bộ thời trang đẹp mắt và cá tính.";
        stringArray2[1] = "Đầu tiên mời bạn vào Shop tham quan. Hãy di chuyển nhân vật đến shop nào.";
        stringArray[0] = stringArray2;
        String[] stringArray3 = new String[2];
        stringArray3[0] = "Đây là nhà bán thú nuôi, nơi bạn có thể lựa chọn cho mình những chú pet thật xinh xắn.";
        stringArray3[1] = "Hãy vào xem một chút nhé!";
        stringArray[1] = stringArray3;
        String[] stringArray4 = new String[2];
        stringArray4[0] = "Bạn có thể vào thay đổi kiểu tóc và mắt của mình tại Thẩm Mỹ Viện.";
        stringArray4[1] = "Hãy vào tham quan thử nhé!";
        stringArray[2] = stringArray4;
        return stringArray;
    }

    public static String[][] java_lang_String_arr_arr_if() {
        String[][] stringArray = new String[7][];
        String[] stringArray2 = new String[6];
        stringArray2[0] = "Đây là nông trại của bạn";
        stringArray2[1] = "Chúng ta sẽ bắt đầu trải nghiệm làm một người nông dân chăm chỉ nhé!";
        stringArray2[2] = "Bạn có thấy những ô đất không?";
        stringArray2[3] = "Đây là khu vực bạn có thể trồng cây.";
        stringArray2[4] = "Bắt đầu thôi nào! Bạn hãy di chuyển đến đó và chọn một ô đất";
        stringArray2[5] = "Hãy chọn mục Làm Đất để xới đất nào!";
        stringArray[0] = stringArray2;
        String[] stringArray3 = new String[2];
        stringArray3[0] = "Chúc mừng! Bạn đã hoàn thành xong việc làm đất";
        stringArray3[1] = "Tiếp theo bạn hãy chọn hạt giống.";
        stringArray[1] = stringArray3;
        String[] stringArray4 = new String[2];
        stringArray4[0] = "Bạn đã gieo hạt. Trên mỗi ô đất có hiển thị thời gian bạn có thể thu hoạch được";
        stringArray4[1] = "Bạn hãy thường xuyên vào tưới nước, bón phân cho cây cho đến khi thu hoạch nhé!";
        stringArray[2] = stringArray4;
        String[] stringArray5 = new String[3];
        stringArray5[0] = "Đây là khu chăn nuôi gia súc.";
        stringArray5[1] = "Bạn cần mua gia súc ngoài cửa hàng và thả nó vào đây";
        stringArray5[2] = "hãy chăm sóc nó, cho ăn và tiêm thuốc bổ đều đặn, đến khi lớn bạn có thể thu hoạch sữa và trứng";
        stringArray[3] = stringArray5;
        String[] stringArray6 = new String[1];
        stringArray6[0] = "Đây là nhà bếp, nơi bạn có thể nấu những món ăn từ nông sản bạn thu hoạch được.";
        stringArray[4] = stringArray6;
        String[] stringArray7 = new String[2];
        stringArray7[0] = "Đây là cây khế, cây khế sẽ cho thu hoạch trong thời gian nhất định.";
        stringArray7[1] = "Hãy nâng cấp cây khế lên càng cao, sản lượng thu hoạch sẽ càng nhiều bạn nhé!";
        stringArray[5] = stringArray7;
        String[] stringArray8 = new String[3];
        stringArray8[0] = "Bạn có thể nuôi cá trong ao này bằng cách mua cá từ cửa hàng bên ngoài";
        stringArray8[1] = "Sau khi thu hoạch cây, vật nuôi, bạn sẽ có một khoản tiền nhỏ trong tài khoản nông trại";
        stringArray8[2] = "Bạn có thể ra ATM để chuyển sang tài khoản chính để có thể dùng nhé!";
        stringArray[6] = stringArray8;
        return stringArray;
    }

    public static String[][] java_lang_String_arr_arr_for() {
        String[][] stringArray = new String[8][];
        String[] stringArray2 = new String[2];
        stringArray2[0] = "Chào mừng bạn đến với khu câu cá.";
        stringArray2[1] = "Có 3 khu câu cá khác nhau, với 3 cấp độ khác nhau";
        stringArray[0] = stringArray2;
        String[] stringArray3 = new String[1];
        stringArray3[0] = "Khu câu cá rô dành cho người mới tập câu";
        stringArray[1] = stringArray3;
        String[] stringArray4 = new String[1];
        stringArray4[0] = "Khu câu cá lóc dành cho các bạn đã biết câu";
        stringArray[2] = stringArray4;
        String[] stringArray5 = new String[1];
        stringArray5[0] = "Khu câu cá mập dành cho các bạn đã là cao thủ câu cá";
        stringArray[3] = stringArray5;
        String[] stringArray6 = new String[1];
        stringArray6[0] = "Để có thể câu cá bạn phải mua cần câu, mồi câu, vé câu";
        stringArray[4] = stringArray6;
        String[] stringArray7 = new String[1];
        stringArray7[0] = "Để có thể mua bạn có thể chat chữ cauca cửa hàng sẽ tự động hiện lên";
        stringArray[5] = stringArray7;
        String[] stringArray8 = new String[1];
        stringArray8[0] = "Hoặc chat chữ banca nếu bạn muốn bán cá";
        stringArray[6] = stringArray8;
        String[] stringArray9 = new String[1];
        stringArray9[0] = "Giờ chúng ta sẽ rời nơi này. Bạn có thể đến đây bất cứ khi nào bạn muốn!";
        stringArray[7] = stringArray9;
        return stringArray;
    }

    static {
        MenuChinhAvatar.void_do();
        ai = "vào";
        bw = "/font.av";
        ap = "/bg.av";
        Z = "/home.av";
        de = "/farm.av";
        bE = "/effect.av";
        bo = "/main.av";
        t = "/dialLucky.av";
        var_java_lang_String_else = "http://";
        O = "@username";
        String[] stringArray = new String[3];
        stringArray[0] = "/normal";
        stringArray[1] = "/medium";
        stringArray[2] = "/hd";
        var_java_lang_String_arr_super = stringArray;
    }

    public static String[][] cfr_renamed_3() {
        String[][] stringArray = new String[1][];
        String[] stringArray2 = new String[1];
        stringArray2[0] = "Hãy gặp thị trưởng để nhận nhiệm vụ và gặp NPC Hội Nhóm để xin gia nhập vào các hội nhóm.";
        stringArray[0] = stringArray2;
        return stringArray;
    }

    public static String[][] cfr_renamed_4() {
        String[][] stringArray = new String[3][];
        String[] stringArray2 = new String[2];
        stringArray2[0] = "Chào mừng bạn đến khu giải trí.";
        stringArray2[1] = "Nơi đây gồm hội quán cờ, Tòa thị chính, Trường đua pet sôi động và các gian hàng quay số may mắn cùng với đấu giá ngược.";
        stringArray[0] = stringArray2;
        String[] stringArray3 = new String[2];
        stringArray3[0] = "Đây là tòa thị chính, nơi bạn có thể nhận những nhiệm vụ trong game và xin gia nhập vào các hội nhóm.";
        stringArray3[1] = "Hãy di chuyển nhân vật đến tham quan tòa thị chính đi nào!";
        stringArray[1] = stringArray3;
        String[] stringArray4 = new String[2];
        stringArray4[0] = "Đây là trường đua thú sôi động. Bạn có thể vào xem những trận đua thú vô cùng hấp dẫn.";
        stringArray4[1] = "Hãy tham quan trường đua trước khi chúng ta di chuyển sang khu vực khác nhé!";
        stringArray[2] = stringArray4;
        return stringArray;
    }

    public static String java_lang_String_do() {
        if ((go_0.var_boolean_int)) {
            return "xèng";
        }
        return da;
    }

    public MenuChinhAvatar() {
        bZ = "Xin chờ";
        bR = "Menu";
        by = "Đóng";
        I = "Đồng ý";
        aa = "Cập nhật";
        cfr_renamed_19 = "Tìm bàn chơi";
        String[] stringArray = new String[6];
        stringArray[0] = "Tiến lên";
        stringArray[1] = "Phỏm";
        stringArray[2] = "Caro";
        stringArray[3] = "Cờ tướng";
        stringArray[4] = "Kim cương";
        stringArray[5] = "Bầu cua";
        var_java_lang_String_arr_case = stringArray;
        String[] stringArray2 = new String[5];
        stringArray2[0] = "Kim cương";
        stringArray2[1] = "Bầu cua";
        stringArray2[2] = "Caro";
        stringArray2[3] = "Cờ tướng";
        stringArray2[4] = "Ongame";
        var_java_lang_String_arr_void = stringArray2;
        String[] stringArray3 = new String[4];
        stringArray3[0] = "Tiến lên";
        stringArray3[1] = "Phỏm";
        stringArray3[2] = "Caro";
        stringArray3[3] = "Cờ tướng";
        cfr_renamed_37 = "Sẵn sàng";
        cS = "Không s.sàng";
        co = "Bắt đầu";
        bL = "Có";
        aB = "Không";
        cY = "Tin nhắn";
        bO = "Đặt tiền cược";
        w = "Đặt số người";
        bs = "Đặt mật khẩu";
        bt = "Rời bàn";
        aM = "Đuổi";
        cW = "Tiếp tục";
        cfr_renamed_34 = "Thoát";
        g = "Kết bạn";
        ct = "OK";
        an = "Đánh";
        var_java_lang_String_class = "Bỏ lượt";
        da = "xu";
        cq = "lượng";
        aW = "Lượng khóa";
        String[] stringArray4 = new String[3];
        stringArray4[0] = "2 người";
        stringArray4[1] = "3 người";
        stringArray4[2] = "4 người";
        var_java_lang_String_arr_long = stringArray4;
        cc = "Sắp bài xong";
        F = "Số tiền cược";
        ag = "Bạn bị đuổi.";
        cfr_renamed_38 = "Đã đặt mật khẩu.";
        ci = "Đối thủ thoát. Bạn thắng";
        bn = "Tới trắng";
        cfr_renamed_46 = "Nhắn tin";
        bS = "Đang kết nối";
        aT = "Đang đăng nhập";
        cT = "Chọn";
        bg = "Bạn có muốn thoát?";
        var_java_lang_String_catch = "Bạn có chắc bỏ lượt?";
        aD = "Bắt buột đánh 3 bích trước.";
        cK = "Không cùng loại hoặc nhỏ hơn bài đang trên bàn.";
        cb = "$";
        aI = " đi trước.";
        tenNhanVat = "Phòng ";
        av = "Tới ";
        String[] stringArray5 = new String[4];
        stringArray5[0] = "Cấp độ chính: ";
        stringArray5[1] = "Cấp độ nông trại: ";
        stringArray5[2] = "Cấp độ";
        stringArray5[3] = "Cấp độ câu cá: ";
        var_java_lang_String_arr_new = stringArray5;
        ca = "Password:";
        v = "Kết nối thất bại. Xin kiểm tra kết nối wifi/3g";
        dl = "Mua";
        bB = "Bạn bè";
        bu = "Cài đặt";
        cfr_renamed_29 = "ăn";
        ar = "Nhận";
        cx = "Hạ Phỏm";
        as = "Bạn chỉ được đánh một lá.";
        var_java_lang_String_void = "Bạn chưa chọn bài.";
        s = "Nếu đánh lá này bạn sẽ phá phỏm";
        bf = "Chờ đến lượt.";
        var_java_lang_String_case = "Không đúng phỏm.";
        MenuChinhAvatar = "Bạn chọn quá nhiều bài.";
        bG = "Không phải là phỏm.";
        z = "Xem thành tích";
        var_java_lang_String_char = "Đến bàn số..";
        i = "Tiền: ";
        aP = "Password:";
        ai = "vao";
        bJ = "Số lượng: ";
        X = "Giá: ";
        bI = "Tên: ";
        chuoiGiaTri = "Quần ";
        cu = "áo ";
        var_java_lang_String_const = "Tóc ";
        bK = "Mắt ";
        var_java_lang_String_try = "Bạn có muốn mua không?";
        String[] stringArray6 = new String[4];
        stringArray6[0] = "Nhảy";
        stringArray6[1] = "Nằm";
        stringArray6[2] = "Ngồi bệt";
        stringArray6[3] = "Quỳ";
        var_java_lang_String_arr_int = stringArray6;
        Q = "Bạn muốn mua bằng gì?";
        db = "TK Chính";
        cA = "Thu nhập: ";
        bv = "Đang lấy dữ liệu nông trại...";
        var_java_lang_String_int = "Đang cập nhật dữ liệu..";
        cD = "Kho hàng";
        String[] stringArray7 = new String[4];
        stringArray7[0] = "Phòng sơ cấp";
        stringArray7[1] = "Phòng trung cấp";
        stringArray7[2] = "Phòng cao thủ";
        stringArray7[3] = "Phòng thi đấu";
        var_java_lang_String_arr_byte = stringArray7;
        cN = "Mất kết nối";
        aL = "Thắng";
        be = "Thua";
        S = "Hòa";
        A = "Bỏ cuộc";
        cfr_renamed_36 = "Đối thủ chưa sẵn sàng";
        cy = " đã thoát";
        String[][] stringArrayArray = new String[5][];
        String[] stringArray8 = new String[3];
        stringArray8[0] = "hiện";
        stringArray8[1] = "ẩn";
        stringArray8[2] = "Tên";
        stringArrayArray[0] = stringArray8;
        String[] stringArray9 = new String[3];
        stringArray9[0] = "hiện";
        stringArray9[1] = "ẩn";
        stringArray9[2] = "Chỉ đường";
        stringArrayArray[1] = stringArray9;
        String[] stringArray10 = new String[3];
        stringArray10[0] = "";
        stringArray10[1] = "";
        stringArray10[2] = "âm thanh";
        stringArrayArray[2] = stringArray10;
        String[] stringArray11 = new String[3];
        stringArray11[0] = "GPRS";
        stringArray11[1] = "Wifi";
        stringArray11[2] = "Kết nối";
        stringArrayArray[3] = stringArray11;
        String[] stringArray12 = new String[3];
        stringArray12[0] = "Tiếng việt";
        stringArray12[1] = "Tiếng Anh";
        stringArray12[2] = "Ngôn ngữ";
        stringArrayArray[4] = stringArray12;
        var_java_lang_String_arr_arr_if = stringArrayArray;
        l = "Xong";
        cfr_renamed_45 = "Khu vực đã đầy.";
        cg = "Khu vực ";
        aY = "Lá bài bạn đánh không có thực.";
        dg = "Năng ít nhất 2 lá để ăn.";
        ce = "Chat";
        cR = "Xóa";
        String[] stringArray13 = new String[8];
        stringArray13[0] = "Khu nhà ở";
        stringArray13[1] = "Khu sinh thái";
        stringArray13[2] = "Sân bay";
        stringArray13[3] = "Khu giải trí";
        stringArray13[4] = "Khu mua sắm";
        stringArray13[5] = "Công viên";
        stringArray13[6] = "Khu ngoại ô";
        stringArray13[7] = "Nông trại";
        var_java_lang_String_arr_short = stringArray13;
        cL = "Đang vào ";
        B = "Tưới nước";
        y = "Làm đất";
        aQ = "Đã hết ";
        var_java_lang_String_byte = "Bán";
        bk = "Bạn muốn phá cây đang có?";
        ax = "Bị tiêu chảy";
        cfr_renamed_42 = "Bị cúm";
        e = "Đói bụng";
        bU = "Mệt quá";
        ac = "Sữa";
        cfr_renamed_11 = "Trứng";
        bl = "Không vào được nông trại.";
        cfr_renamed_41 = "Bạn có muốn bán";
        var_java_lang_String_this = " Giờ";
        bc = "Giống";
        dn = "Vật Phẩm";
        L = "Không thể vào.";
        dp = "Kho Giống";
        bM = "Bạn đã bị bắt.";
        u = "Hết thức ăn.";
        cfr_renamed_26 = "Tiền bán nông sản: ";
        M = "Bản thân";
        cfr_renamed_43 = "Tiếp";
        var_java_lang_String_super = "Nhớ";
        h = "Đăng ký";
        cG = "Quên mật khẩu";
        cJ = "Tên tài khoản";
        b = "Hỗ trợ";
        cfr_renamed_33 = "Xóa bộ nhớ tạm";
        cfr_renamed_32 = "Đã";
        bF = "Bạn phải dùng số điện thoại đăng ký tài khoản để lấy mật khẩu.";
        al = "Bỏ";
        n = "Không đồng ý";
        aS = "Xem điều khoản";
        aw = "Bạn phải chấp nhận điều khoản.";
        cQ = "Tài khoản:";
        aA = "Mật khẩu";
        cF = "Chọn T. Phố";
        dj = "Nhớ mật khẩu";
        FormCaiDatCauCa = "Sự kiện";
        cP = "Tặng quà";
        cfr_renamed_39 = "Đánh";
        ab = "Hôn";
        GameCanvas = "Xem thông tin";
        bz = "Nhắn tin riêng";
        bp = "Hành động";
        bW = "Cảm xúc";
        au = "Giao dịch";
        az = " tặng hoa rơi cho ";
        cfr_renamed_40 = " với ";
        cI = "Từ chối";
        String[][] stringArrayArray2 = new String[2][];
        String[] stringArray14 = new String[2];
        stringArray14[0] = "Số seri:";
        stringArray14[1] = "";
        stringArrayArray2[0] = stringArray14;
        String[] stringArray15 = new String[2];
        stringArray15[0] = "Mã số thẻ:";
        stringArray15[1] = "";
        stringArrayArray2[1] = stringArray15;
        var_java_lang_String_arr_arr_do = stringArrayArray2;
        String[] stringArray16 = new String[6];
        stringArray16[0] = "C.Độ: ";
        stringArray16[1] = "T.Thiện";
        stringArray16[2] = "G.Rối";
        stringArray16[3] = "S.Điệu";
        stringArray16[4] = "V.Vẻ";
        stringArray16[5] = "S.Khỏe";
        var_java_lang_String_arr_const = stringArray16;
        dh = "Chỉ số";
        chuoiPhu = "Hiện có: ";
        String[] stringArray17 = new String[3];
        stringArray17[0] = "Nạp tiền";
        stringArray17[1] = "Chuyển tiền";
        stringArray17[2] = "Bản thân";
        var_java_lang_String_arr_goto = stringArray17;
        String[] stringArray18 = new String[2];
        stringArray18[0] = "TK chính sang nông trại";
        stringArray18[1] = "TK nông trại sang chính";
        var_java_lang_String_arr_float = stringArray18;
        var_java_lang_String_break = "NẠP TIỀN";
        aE = "Tin đến";
        cfr_renamed_44 = "Đóng tab";
        cfr_renamed_27 = "Bắt đầu chat với ";
        V = "Xong";
        N = "Tạo nhân vật";
        String[] stringArray19 = new String[2];
        stringArray19[0] = "Nam";
        stringArray19[1] = "Nữ";
        var_java_lang_String_arr_else = stringArray19;
        J = "Tạo nhân vật không thành công.";
        aN = "Hủy";
        bq = "co the thu hoach";
        bh = "Rương đồ";
        br = "Bỏ món đồ này ?";
        String[] stringArray20 = new String[4];
        stringArray20[0] = "Bỏ vào rương ?";
        stringArray20[1] = "Sử dụng vật phẩm này ?";
        stringArray20[2] = "Bỏ vào giỏ đồ ?";
        stringArray20[3] = "Bỏ vào rương ?";
        var_java_lang_String_arr_if = stringArray20;
        cB = "Di chuyển";
        R = "Độ bền: ";
        cz = "Sử dụng";
        FormCaiDatFarm = "Đã gửi tin nhắn.";
        bb = "Không thể gửi tin nhắn.";
        Y = "Nếu thoát bạn sẽ bị xử thua. Bạn có muốn thoát?";
        String[] stringArray21 = new String[3];
        stringArray21[0] = "Nghe nhỏ";
        stringArray21[1] = "Nghe vừa";
        stringArray21[2] = "Nghe lớn";
        var_java_lang_String_arr_try = stringArray21;
        String[] stringArray22 = new String[7];
        stringArray22[0] = "Cóc";
        stringArray22[1] = "Sảnh";
        stringArray22[2] = "Đôi";
        stringArray22[3] = "Ba lá";
        stringArray22[4] = "Ba đôi thông";
        stringArray22[5] = "Bốn đôi thông";
        stringArray22[6] = "Tứ quý";
        var_java_lang_String_arr_for = stringArray22;
        String[] stringArray23 = new String[8];
        stringArray23[0] = "Chặt heo đen";
        stringArray23[1] = "Chặt heo đỏ";
        stringArray23[2] = "Chặt đôi heo đen";
        stringArray23[3] = "Chặt đôi heo đỏ";
        stringArray23[4] = "Chặt đôi heo 1 đen 1 đỏ";
        stringArray23[5] = "Chặt 3 đôi thông";
        stringArray23[6] = "Chặt tứ quý";
        stringArray23[7] = "Chặt 4 đôi thông";
        bD = "Thông tin";
        aj = "Đổi mật khẩu";
        String[][] stringArrayArray3 = new String[3][];
        String[] stringArray24 = new String[2];
        stringArray24[0] = "Mật khẩu";
        stringArray24[1] = "Cũ";
        stringArrayArray3[0] = stringArray24;
        String[] stringArray25 = new String[2];
        stringArray25[0] = "Mật khẩu";
        stringArray25[1] = "Mới";
        stringArrayArray3[1] = stringArray25;
        String[] stringArray26 = new String[2];
        stringArray26[0] = "Nhập lại";
        stringArray26[1] = "Mật khẩu";
        stringArrayArray3[2] = stringArray26;
        var_java_lang_String_arr_arr_for = stringArrayArray3;
        aC = "Xong";
        String[] stringArray27 = new String[5];
        stringArray27[0] = "Xin nhập mật khẩu hiện tại.";
        stringArray27[1] = "Xin nhập mật khẩu mới.";
        stringArray27[2] = "Xin nhập lại mật khẩu mới.";
        stringArray27[3] = "Hai mật khẩu mới phải giống nhau.";
        stringArray27[4] = "Mật khẩu mới phải khác mật khẩu cũ.";
        var_java_lang_String_arr_char = stringArray27;
        E = "Quăng câu";
        var_java_lang_String_goto = "Cắn câu";
        cfr_renamed_35 = "Trật rồi";
        j = "Số cá câu được: ";
        aq = "Thành tích";
        String[] stringArray28 = new String[4];
        stringArray28[0] = "Bạn chưa nhập tên";
        stringArray28[1] = "Bạn chưa nhập mật khẩu";
        stringArray28[2] = "Bạn chưa nhập lại mật khẩu.";
        stringArray28[3] = "Hai mật khẩu không giống nhau.";
        var_java_lang_String_arr_class = stringArray28;
        var_java_lang_String_final = "Nhập lại";
        String[] stringArray29 = new String[2];
        stringArray29[0] = "Hoa rơi";
        stringArray29[1] = "Tim bay";
        H = "Gui cho ban be";
        at = "So dien thoai";
        aU = "Ban co the chon so dien thoai tu Menu / Danh ba";
        dc = "Bạn có muốn nâng cấp giỏ đồ không ?";
        aK = "Bạn có muốn thoát game để vào mục này không?";
        String[] stringArray30 = new String[2];
        stringArray30[0] = "Bạn chưa nhập số seri.";
        stringArray30[1] = "Bạn chưa nhập mã số thẻ.";
        var_java_lang_String_arr_catch = stringArray30;
        x = "ngày";
        bN = "Thức ăn";
        am = "Quay số";
        cr = "Vĩnh viễn";
        aV = "Bạn muốn mua vật phẩm này với giá";
        bV = "Đặt";
        bP = "Chỉnh sửa nhà";
        o = "Mua đồ";
        ah = "lát gạch, sơn tường";
        q = "Chuyển, bán đồ";
        cw = "Không có vật phẩm ở đây";
        bY = "Di chuyển";
        p = "Xoay";
        cfr_renamed_22 = "Bạn có muốn bán?";
        P = "Bạn không được đặt ở đây.";
        r = "Đã có vật phẩm";
        d = "Phải đặt sát tường.";
        cfr_renamed_24 = "Không có bạn trong khu này.";
        cl = "Về nhà";
        ck = "Vào nhà bạn bè";
        bm = "cho";
        cV = "tặng";
        U = "Mời đến nhà";
        bj = "Nâng cấp giỏ đồ";
        T = "Bạn bị chủ nhà đuổi.";
        ba = "Cháy";
        bT = "Ù";
        dd = "Đền ù";
        cfr_renamed_31 = "Bạn được mời về nhà bởi ";
        aJ = "Bạn có muốn không ?";
        cf = "Giỏ đồ";
        f = " Để chọn ngôn ngữ vui lòng khởi động lại game.";
        ad = "Quay";
        String[] stringArray31 = new String[5];
        stringArray31[0] = "Tiến Lên";
        stringArray31[1] = "Phỏm";
        stringArray31[2] = "Kim Cương";
        stringArray31[3] = "Bầu Cua";
        stringArray31[4] = "Chuyển tiền";
        var_java_lang_String_arr_this = stringArray31;
        aO = "Quay về";
        af = "Đang mặc";
        cU = "C.độ yêu cầu: ";
        cE = "Quà";
        bH = "Xin chào ";
        ae = "Dừng";
        var_java_lang_String_new = "Bạn có muốn xem hướng dẫn chơi game không ?";
        bd = "Bạn có chắc muốn dừng hướng dẫn không?";
        dk = "Nấu ăn";
        ch = "Đang nấu";
        var_java_lang_String_long = "Bạn có muốn hủy món đang nấu không?";
        cH = "Không đủ ";
        bA = "Giá bán: ";
        ak = "Nguyên liệu: ";
        var_java_lang_String_short = "Hoàn thành";
        cZ = "Nấu ăn nhanh";
        a = "Thời gian: ";
        cd = "Nâng cấp nhanh";
        k = "Nâng cấp";
        K = "Thu hoạch";
        c = "Tk game: ";
        cs = "Quan hệ";
        cC = "Kho của bạn đã hết hạt giống, xin vào cửa hàng đễ mua.";
        bC = "Kho của bạn đã hết thuốc, xin vào cửa hàng đễ mua.";
        QuanLyRMS = "Bạn có muốn nâng cấp kho hàng không ?";
        cj = "Không có vật nuôi nào bị bệnh";
        cfr_renamed_25 = "ô này không có cây.";
        cfr_renamed_17 = "ô này không có cây.";
        D = "Hãy chọn ô không có cây hoặc cây đã chết.";
        aH = "Kho của bạn đã hết phân bón, xin vào cửa hàng đễ mua.";
        df = "Lông";
        m = "Sản phẩm";
        dm = "Sản lượng";
        cm = "Chăm sóc vật nuôi";
        cO = "Gieo hạt";
        bi = "Chăm sóc cây trồng";
        aR = "Trị bệnh";
        ao = "Kho của bạn đã hết thuốc tiêu chảy, xin vào cửa hàng đễ mua.";
        var_java_lang_String_float = "Kho của bạn đã hết thuốc cúm, xin vào cửa hàng đễ mua.";
        cX = "Cho ăn";
        di = "Kho của bạn đã hết thức ăn, xin vào cửa hàng đễ mua.";
        C = "Thuốc bổ";
        cv = "Kho của bạn đã hết thuốc bổ, xin vào cửa hàng đễ mua.";
        cfr_renamed_28 = "Bạn có muốn bất đầu lể cưới không ?";
        String[] stringArray32 = new String[3];
        stringArray32[0] = "Lễ cưới của chú rể ";
        stringArray32[1] = " và cô dâu ";
        stringArray32[2] = " chính thức bắt đầu.  mời Cô Dâu và Chú rể cùng tiến về lễ đường.";
        var_java_lang_String_arr_do = stringArray32;
        String[] stringArray33 = new String[4];
        stringArray33[0] = "Hôm nay chúng ta có mặt tại đây để cùng chúc mừng cho đám cưới của chú rể ";
        stringArray33[1] = "Vượt qua bao khó khăn thử thách bằng tình yêu vĩnh cửu, sau cùng cả hai đã đạt đến bến bờ hạnh phúc.";
        stringArray33[2] = "Kể từ hôm nay, ta tuyên bố 2 bạn chính thức trở thành vợ chồng.";
        stringArray33[3] = "Chú rể có thể hôn Cô Dâu.";
        var_java_lang_String_arr_final = stringArray33;
        aF = "Đặt cược";
        aX = "Lịch sử";
        cM = "Bạn có muốn thoát không ?";
        W = "Bạn có muốn thoát không (nếu có đặt cược bạn sẽ mất tiền cược) ?";
        aZ = "Bản đặt cược";
        String[] stringArray34 = new String[3];
        stringArray34[0] = "Thấp";
        stringArray34[1] = "Thường";
        stringArray34[2] = "Cao";
        var_java_lang_String_arr_break = stringArray34;
        G = "Tỉ lệ";
        bX = "Phong độ";
        aG = "Sức khỏe";
    }

    public static String[][] cfr_renamed_5() {
        String[][] stringArray = new String[6][];
        String[] stringArray2 = new String[4];
        stringArray2[0] = "Chào mừng bạn đến với Avatar - Thành phố diệu kỳ";
        stringArray2[1] = "Chúng ta sẽ dạo một vòng qua thành phố này nhé!";
        stringArray2[2] = "Thành phố có rất nhiều khu, chúng ta sẽ đến từng khu để tìm hiểu";
        stringArray2[3] = "Khu Giải Trí là nơi nào nhiệt nhất thành phố. Mời bạn chọn vào nào!";
        stringArray[0] = stringArray2;
        String[] stringArray3 = new String[2];
        stringArray3[0] = "Nông Trại là nơi trồng trọt và chăn nuôi, bạn có thể tăng thêm thu nhập";
        stringArray3[1] = "Bạn hãy chọn vào mục Nông Trại nào";
        stringArray[1] = stringArray3;
        String[] stringArray4 = new String[2];
        stringArray4[0] = "Tiếp theo là khu Mua Sắm, nơi mà bạn có thể lựa chọn cho mình những bộ trang phục đẹp mắt.";
        stringArray4[1] = "Chọn vào tham quan khu Mua Sắm ngay bạn nhé!";
        stringArray[2] = stringArray4;
        String[] stringArray5 = new String[2];
        stringArray5[0] = "Tiếp theo là khu Sinh Thái, nơi mà bạn có thể thư giãn với việc câu cá";
        stringArray5[1] = "Mời bạn chọn vào Khu Sinh Thái";
        stringArray[3] = stringArray5;
        String[] stringArray6 = new String[2];
        stringArray6[0] = "Khu vực Công Viên là nơi bạn có thể gặp gỡ và trò chuyện với bạn bè";
        stringArray6[1] = "Bạn có thể vào thử Công Viên. Sau khi dạo một vòng hãy đến Trạm Xe Buýt để trở lại nơi này nhé!";
        stringArray[4] = stringArray6;
        String[] stringArray7 = new String[2];
        stringArray7[0] = "Thành phố diệu kỳ còn rất nhiều khu khác để bạn khám phá. Hãy ghé qua khu sân bay thường xuyên để cập nhật các địa điểm mới";
        stringArray7[1] = "Giờ bạn có thể vào nông trại, vào hội cờ, đi mua sắm,đi câu cá, hoặc làm bất kỳ điều gì bạn thích. Cám ơn bạn đã xem hướng dẫn!";
        stringArray[5] = stringArray7;
        return stringArray;
    }

    public static String java_lang_String_if() {
        if ((go_0.var_boolean_int)) {
            return "xeng";
        }
        return da;
    }

    public static String java_lang_String_for() {
        return var_java_lang_String_arr_super[GameCanvas.cfr_renamed_12];
    }

    private static void void_do() {
        mangSoNguyen = new int[9];
        3 = "   ".length();
        0 = (0x30 ^ 0x1F) & ~(0x86 ^ 0xA9);
        1 = " ".length();
        2 = "  ".length();
        6 = 0x22 ^ 0x3D ^ (0xDE ^ 0xC7);
        4 = 0x3A ^ 0x3E;
        5 = 0xD8 ^ 0xB9 ^ (0xCB ^ 0xAF);
        8 = 0x9E ^ 0x96;
        7 = 0x23 ^ 0x24;
    }

    public static String[][] cfr_renamed_6() {
        String[][] stringArray = new String[4][];
        String[] stringArray2 = new String[3];
        stringArray2[0] = "Khu vực nông trại có 4 nơi bạn có thể vào: Cửa hàng, ATM, Nông trại của mình, và Nông trại của bạn bè.";
        stringArray2[1] = "Cửa hàng là nơi bạn mua hạt giống, vật nuôi và các vật phẩm khác";
        stringArray2[2] = "Tại sao bạn lại không thử mua một ít hạt giống nhỉ?";
        stringArray[0] = stringArray2;
        String[] stringArray3 = new String[2];
        stringArray3[0] = "Hiện tại trong người của bạn có sẵn vài hạt giống. Nhưng bạn vẫn có thể mua thêm hạt giống khác nếu thích.";
        stringArray3[1] = "Hãy chọn mua thử nào!";
        stringArray[1] = stringArray3;
        String[] stringArray4 = new String[2];
        stringArray4[0] = "Hãy chọn số lượng muốn mua";
        stringArray4[1] = "Sau khi mua xong, bạn hãy chọn Đóng để rời khỏi cửa hàng";
        stringArray[2] = stringArray4;
        String[] stringArray5 = new String[2];
        stringArray5[0] = "Chúng ta đã có một số hạt giống rồi!";
        stringArray5[1] = "Hãy bước vào khu vực nông trại của bạn để bắt đầu gieo hạt!";
        stringArray[3] = stringArray5;
        return stringArray;
    }

    public static String[][] cfr_renamed_7() {
        String[][] stringArray = new String[2][];
        String[] stringArray2 = new String[2];
        stringArray2[0] = "Chào mừng bạn đến với cửa hàng quần áo.";
        stringArray2[1] = "Hãy bước đến gặp người bán hàng để thử quần áo, bạn nhớ chú ý giá cả nhé!";
        stringArray[0] = stringArray2;
        String[] stringArray3 = new String[2];
        stringArray3[0] = "Sử dụng các mũi tên để chọn các bộ quần áo khác nhau";
        stringArray3[1] = "Nếu bạn có đủ tiền, hãy chọn mua một bộ quần áo mới";
        stringArray[1] = stringArray3;
        return stringArray;
    }
}

